### PR TITLE
Fix TypeError when SpeechRecognition API is not supported by the browser

### PR DESCRIPTION
**Pull request by masonlouchart**

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @masonlouchart, I'm not maintaining this project anymore. Would you like to be a collaborator?

**Comment by masonlouchart** [comment]
Hi @zenorocha , sure why not ?! 😄

**Comment by zenorocha** [comment]
Cool, invitation sent! You can now merge pull requests and close issues ;)

**Comment by masonlouchart** [comment]
Thanks! 😉👌

**Pull request merged**
